# Generated by Django 3.0.6 on 2020-06-12 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SZM', '0002_product_mydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 12, 8, 45, 1, 89596)),
        ),
    ]
