# Generated by Django 3.0.6 on 2020-06-15 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SZM', '0003_auto_20200612_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 15, 22, 31, 10, 212168)),
        ),
    ]
