# Generated by Django 3.0.6 on 2020-06-16 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SZM', '0004_auto_20200615_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='age',
        ),
        migrations.RemoveField(
            model_name='product',
            name='currency',
        ),
        migrations.AlterField(
            model_name='product',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 18, 33, 23, 110428)),
        ),
    ]
